### ISSUE TITLE
migrate reset fails on MS SQL server

### ISSUE THREAD

**Issue by wpdebruin** [commandbox-modules/commandbox-migrations#12]
When executing `migrate reset` it refuses to do so
This database grammar does not support this operation
compileDropAllObjects

When renaming my existing cfmigrations table and trying  to init it refuses to do so because the explicit name of a constraint
There is already an object named 'pk_cfmigrations_name' in the database. I guess this name is explicitly given by cfmigrations,  but for this also a random name would be OK.

Database version MSSQL 12.0.4100.1. Didn't check other versions

**Comment by elpete** [comment]
The `dropAllObjects` is coming to SqlServer and Oracle in the next version of qb (7.0.0).  Once that drops, this functionality will work for your grammar.
