### ISSUE TITLE
Run box.json checks only on applicable tasks

### ISSUE THREAD

**Issue by jclausen** [commandbox-modules/commandbox-migrations#20]
The bundle key checks ( https://github.com/commandbox-modules/commandbox-migrations/blob/master/models/BaseMigrationCommand.cfc#L58 ) added for CommandBox 5 fire on all cfmigrations tasks, on all DBMS platforms.  According to the documentation these keys are only applicable to MySQL.   

In addition, they key checks for the `box.json` file run on all tasks, regardless of whether the database is being engaged in the command or not ( e.g. `migrate create` )

As some users may be using this module to scaffold migrations, while running migrations, themselves, from within the app, refactor these to only fire when applicable.

**Comment by elpete** [comment]
Published as v3.1.4
