### ISSUE TITLE
Add more debugging when connections don't work

### ISSUE THREAD

**Issue by lmajano** [commandbox-modules/commandbox-migrations#24]
As it stands, the errors when having connection issues are not nice.

```
❯ migrate install


ERROR (5.0.2-alpha+00170)

Could not create connection to database server.
```

Nothing more nothing less.  Looks like a hibernate error :(

We need to improve these error messages and show WHY we could not connect.

**Comment by Daemach** [comment]
And also some kind of indication of which migration file failed in the case of SQL errors.  A simple dump of the filename while spooling through the migrations would work.  As an example, which of the 6 migrations that needed to run here failed?  https://www.screencast.com/t/ATWzEPeeTx0I

**Comment by elpete** [comment]
@lmajano To get the full exception information, use `--verbose`

**Comment by elpete** [comment]
@Daemach That is a good suggestion.  I'll add a new ticket for it.
