### ISSUE TITLE
migrate up throwing dbase error

### ISSUE THREAD

**Issue by Daemach** [commandbox-modules/commandbox-migrations#25]
I am trying to "migrate up" from commandbox.  I get the following error: https://www.screencast.com/t/JmsfGarVgoxz

I added this section to the commandbox-migrations box.json as described on the github readme page and reloaded commandbox but same error.  https://www.screencast.com/t/DEeJMoG4aF

**Comment by elpete** [comment]
It needs to be added to your app's `box.json`, not the module's.

**Comment by Daemach** [comment]
Thank you!
