### ISSUE TITLE
Add seed commands for CLI

### ISSUE THREAD

**Issue by jclausen** [commandbox-modules/commandbox-migrations#30]
Add commands to create and run seeds from the CLI.

Suggest the following syntax:

`migrate create seed [Seed Name]`
`migrate fresh --seed`
`migrate up --seed [ optional seed name ]`

If it is too difficult to change the method signature for the `create` action, however, the first command might be

`migrate seed create [Seed Name]`

**Comment by elpete** [comment]
Fixed in 4.0.0
