### ISSUE TITLE
Migration files are not created in the correct location. 

### ISSUE THREAD

**Issue by Daemach** [commandbox-modules/commandbox-migrations#38]
![image](https://user-images.githubusercontent.com/12553953/193935745-ae41e66a-4aeb-40a5-a6fa-d3ed1d0558ed.png)

**Comment by Daemach** [comment]
There is no F_Drive folder, but it created one and put the migration there.
![image](https://user-images.githubusercontent.com/12553953/193935995-9786c5db-a327-4b07-98fb-3a6af986aa04.png)

**Comment by Daemach** [comment]
`Migrate up` is pulling from that f_drive folder too, rather than within the site root.

**Comment by elpete** [comment]
Should be fixed in v4.0.4
