### ISSUE TITLE
migrate seed failing after update today

### ISSUE THREAD

**Issue by powertoaster** [commandbox-modules/commandbox-migrations#41]
`migrate seed run manager="adilas" name="dataDictionary"
Error executing command [migrate seed run manager="adilas" name="dataDictionary"], exiting recipe.

ERROR (5.9.0+00721)

Component [C__Users_power__CommandBox.cfml.modules.commandbox-migrations.commands.migrate.seed.run] has no accessible Member with name [CFMIGRATIONSINFOTYPE]

\modules\commandbox-migrations\commands\migrate\seed\run.cfc: line 18
16:         setup( arguments.manager );
17:
18:         if ( variables.cfmigrationsInfoType == "boxJSON" ) {
19:             error( "Seeders can only be ran after migrating to the new v4 migrations configuration." );
20:         }`

**Comment by elpete** [comment]
Fixed in latest (v5.0.3)
